-- Delete existing demo store products
DELETE FROM products WHERE store_id = 'e1eb9c10-8823-41d1-961a-776b6d7d9b8d';

-- Insert 12 new demo products
INSERT INTO products (store_id, title, description, price, currency, image_urls, is_active, delivery_info, checkout_fields) VALUES
-- Electronics
('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Premium Wireless Headphones', 'Immerse yourself in studio-quality sound with our premium wireless headphones. Featuring active noise cancellation, 30-hour battery life, and ultra-comfortable memory foam ear cushions. Perfect for music lovers, gamers, and professionals who demand exceptional audio quality.', 149.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Portable Bluetooth Speaker', 'Take your music anywhere with this powerful portable speaker. Waterproof IPX7 design, 360-degree sound, and 20-hour battery life make it perfect for outdoor adventures, beach days, or backyard parties. Deep bass and crystal-clear highs.', 79.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Smart Watch Pro', 'Track your fitness, monitor your health, and stay connected with this advanced smart watch. Features include heart rate monitoring, GPS tracking, sleep analysis, and smartphone notifications. Water-resistant with 7-day battery life. Compatible with iOS and Android.', 299.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

-- Fashion & Accessories
('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Designer Sunglasses', 'Elevate your style with these luxury polarized sunglasses. UV400 protection shields your eyes, while the lightweight titanium frame ensures all-day comfort. Scratch-resistant lenses and spring hinges. Comes with premium carrying case and microfiber cleaning cloth.', 189.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Genuine Leather Wallet', 'Handcrafted from premium full-grain Italian leather, this minimalist wallet features RFID blocking technology to protect your cards. Includes 8 card slots, 2 bill compartments, and a slim profile that fits comfortably in any pocket. Ages beautifully over time, developing a rich patina.', 69.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Cashmere Blend Scarf', 'Luxuriously soft cashmere blend scarf perfect for any season. 70% cashmere, 30% silk blend provides warmth without bulk. Available in elegant neutral tones. Measures 70 x 12 inches. Hand wash or dry clean. Makes an excellent gift for any occasion.', 89.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

-- Home & Lifestyle
('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Organic Cotton Bedding Set', 'Transform your bedroom into a luxury retreat with this 100% GOTS-certified organic cotton bedding set. Includes fitted sheet, flat sheet, and two pillowcases. Breathable, hypoallergenic, and gets softer with each wash. 400 thread count. Available in Queen and King sizes.', 129.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Artisan Ceramic Mug Set', 'Handcrafted ceramic mug set featuring unique reactive glazed finishes. Each mug holds 12oz and is microwave and dishwasher safe. Set includes 4 mugs, each with a distinct earth-tone color. Made by local artisans using sustainable practices. Perfect for coffee, tea, or hot chocolate.', 49.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Aromatherapy Candle Collection', 'Premium soy wax candle collection with pure essential oil blends. Three signature scents: Lavender Dreams (relaxing), Citrus Burst (energizing), and Sandalwood Serenity (grounding). Burns for 50+ hours each. Hand-poured in small batches. Cotton wicks, non-toxic.', 59.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

-- Beauty & Wellness
('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Luxury Skincare Set', 'Complete 4-step anti-aging skincare routine featuring vitamin C serum, hyaluronic acid moisturizer, gentle foaming cleanser, and overnight repair cream. Dermatologist-tested, cruelty-free, and formulated for all skin types. Clinically proven to reduce fine lines and improve radiance.', 119.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

-- Sports & Fitness
('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Professional Yoga Mat', 'Professional-grade yoga mat with superior grip and cushioning. 6mm thick eco-friendly TPE material provides joint protection. Non-slip texture on both sides works on any surface. Includes carrying strap and online workout guide. Perfect for yoga, Pilates, stretching, and meditation.', 69.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb),

('e1eb9c10-8823-41d1-961a-776b6d7d9b8d', 'Insulated Water Bottle', 'Stay hydrated in style with this premium stainless steel water bottle. Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12 hours. 32oz capacity, leak-proof flip-top lid, and wide mouth for easy cleaning. BPA-free and dishwasher safe. Available in 6 colors.', 34.99, 'USD', '[]'::jsonb, true, 'This is a demo product. No actual checkout available.', '{"name": false, "email": false, "phone": false, "address": false, "wallet": false, "custom_fields": []}'::jsonb)