-- Add descriptions to historical sims
UPDATE advisors SET description = 'Discuss economics, free markets, and the invisible hand of capitalism' WHERE name = 'Adam Smith';
UPDATE advisors SET description = 'Discuss World War II history, totalitarianism, and the rise of fascism' WHERE name = 'Adolf Hitler';
UPDATE advisors SET description = 'Discuss Eastern philosophy, consciousness, and the nature of reality' WHERE name = 'Alan Watts';
UPDATE advisors SET description = 'Discuss physics, relativity, and the fundamental nature of the universe' WHERE name = 'Albert Einstein';
UPDATE advisors SET description = 'Discuss crypto culture, memecoins, and building web3 platforms' WHERE name = 'Alon';
UPDATE advisors SET description = 'Discuss aviation history, courage, and breaking barriers for women' WHERE name = 'Amelia Earhart';
UPDATE advisors SET description = 'Discuss logic, ethics, metaphysics, and the foundations of Western philosophy' WHERE name = 'Aristotle';
UPDATE advisors SET description = 'Discuss objectivism, rational self-interest, and individual rights' WHERE name = 'Ayn Rand';
UPDATE advisors SET description = 'Discuss enlightenment, mindfulness, and the path to ending suffering' WHERE name = 'Buddha';
UPDATE advisors SET description = 'Discuss evolution, natural selection, and the origin of species' WHERE name = 'Charles Darwin';
UPDATE advisors SET description = 'Discuss quantum physics, wholeness, and the implicate order of reality' WHERE name = 'David Bohm';
UPDATE advisors SET description = 'Discuss military strategy, empire building, and conquering vast territories' WHERE name = 'Genghis Khan';
UPDATE advisors SET description = 'Discuss American independence, leadership, and founding a nation' WHERE name = 'George Washington';
UPDATE advisors SET description = 'Discuss freedom, the Underground Railroad, and the fight against slavery' WHERE name = 'Harriet Tubman';
UPDATE advisors SET description = 'Discuss institutional critique, education reform, and convivial society' WHERE name = 'Ivan Illich';
UPDATE advisors SET description = 'Discuss love, compassion, salvation, and the kingdom of God' WHERE name = 'Jesus Christ';
UPDATE advisors SET description = 'Discuss consciousness research, dolphins, and exploring inner space' WHERE name = 'John C. Lilly';
UPDATE advisors SET description = 'Discuss communism, class struggle, and critiques of capitalism' WHERE name = 'Karl Marx';
UPDATE advisors SET description = 'Discuss art, science, engineering, and Renaissance innovation' WHERE name = 'Leonardo da Vinci';
UPDATE advisors SET description = 'Discuss civil rights, Black nationalism, and revolutionary activism' WHERE name = 'Malcolm X';
UPDATE advisors SET description = 'Discuss stoicism, duty, leadership, and philosophical reflection' WHERE name = 'Marcus Aurelius';
UPDATE advisors SET description = 'Discuss conservatism, leadership, and British politics' WHERE name = 'Margaret Thatcher';
UPDATE advisors SET description = 'Discuss radioactivity, scientific discovery, and breaking barriers for women in science' WHERE name = 'Marie Curie';
UPDATE advisors SET description = 'Discuss faith, devotion, and the life of Jesus Christ' WHERE name = 'Mary Magdalene';
UPDATE advisors SET description = 'Discuss free markets, monetary policy, and economic liberty' WHERE name = 'Milton Friedman';
UPDATE advisors SET description = 'Discuss military strategy, French history, and imperial ambition' WHERE name = 'Napoleon';
UPDATE advisors SET description = 'Discuss extremism, terrorism, and geopolitical conflict' WHERE name = 'Osama bin Laden';
UPDATE advisors SET description = 'Discuss the drug trade, organized crime, and Colombian history' WHERE name = 'Pablo Escobar';
UPDATE advisors SET description = 'Discuss cubism, modern art, and creative innovation' WHERE name = 'Pablo Picasso';
UPDATE advisors SET description = 'Discuss philosophy, the Forms, and the ideal republic' WHERE name = 'Plato';
UPDATE advisors SET description = 'Discuss design science, synergetics, and comprehensive solutions for humanity' WHERE name = 'R. Buckminster Fuller';
UPDATE advisors SET description = 'Discuss mimetic theory, violence, and the scapegoat mechanism' WHERE name = 'René Girard';
UPDATE advisors SET description = 'Discuss quantum mechanics, physics education, and the joy of discovery' WHERE name = 'Richard Feynman';
UPDATE advisors SET description = 'Discuss interdimensional science, nihilism, and reckless adventures' WHERE name = 'Rick Sanchez';
UPDATE advisors SET description = 'Discuss theology, grace, free will, and early Christian thought' WHERE name = 'St. Augustine';
UPDATE advisors SET description = 'Discuss psychedelics, ethnobotany, and the archaic revival' WHERE name = 'Terence McKenna';
UPDATE advisors SET description = 'Discuss theology, natural law, and the synthesis of faith and reason' WHERE name = 'Thomas Aquinas';
UPDATE advisors SET description = 'Discuss democracy, liberty, and the American founding principles' WHERE name = 'Thomas Jefferson';
UPDATE advisors SET description = 'Discuss imagination, storytelling, and building magical experiences' WHERE name = 'Walt Disney';
UPDATE advisors SET description = 'Discuss poetry, drama, and the human condition through theater' WHERE name = 'William Shakespeare';
UPDATE advisors SET description = 'Discuss leadership, World War II, and British resolve' WHERE name = 'Winston Churchill';