// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcdrsupwwitlvrvfrgsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZHJzdXB3d2l0bHZydmZyZ3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MDY0OTgsImV4cCI6MjA1OTQ4MjQ5OH0.upRoe4x05QnM_zWG6SbJS6BhJzqqCpnH0hCWF_l3v4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});